const express = require('express')
const router = express.Router()
const productController = require('../app/controllers/productController')
const upload = require('../app/middlewares/uploadMiddleware')

router.get('/get-list-of-all-products', productController.getAllProducts)
router.get('/get-detailed-information-of-a-product', productController.getProductById)
router.post('/add-a-new-product', upload.single('image'), productController.addProduct)
router.put('/update-product-information', productController.updateProduct)
router.delete('/remove-product-from-system', productController.deleteProduct)
router.get('/get-product-list-by-category', productController.getProductsByCategory)
router.get('/get-a-list-of-products-from-a-supplier', productController.getProductsBySupplier)
router.get('/get-nearly-expired-products', productController.getNearlyExpiredProducts)
router.get('/get-expired-products', productController.getExpiredProducts)
router.get('/get-products-by-brand', productController.getProductsByBrand)
router.get('/get-products-by-unit', productController.getProductsByUnit)
router.get('/get-all-brands', productController.getAllBrands)
router.get('/get-all-units', productController.getAllUnits)

module.exports = router